apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion-js-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-src
          image: saimonribeiros/motion-js
---
apiVersion: v1
kind: Service
metadata:
  name: motion-js-srv
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - name: my-src
      port: 3000
      targetPort: 3000


