apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-motion-api
  labels:
    type: go-motion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-motion-api
  template:
    metadata:
      labels:
        app: go-motion-api
    spec:
      containers:
        - name: go-motion-api
          image: saimonribeiros/motion-app:latest
          ports:
            - containerPort: 8080